# Site Info
title:              "website"
description:        "personal website of Willi Ballenthin"
#google_verify:      # Put your Google Verification here
google_analytics:   UA-23141359-1

# Author Info
author_name:        "Willi Ballenthin"
author_email:       willi.ballenthin@gmail.com
author_gravatar:    677f6ada59932964b9150aba814fedd6 # Gravatar md5 hash
twitter_username:   williballenthin

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /blog/:year/:month/:day/:title/
timezone:           America/New_York

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]
