baseURL = 'http://www.williballenthin.com'
languageCode = 'en-us'
title = 'Willi Ballenthin'

theme = 'wb'

googleAnalytics = 'G-354515685'

[permalinks]
  # use old post path to keep existing links working
  posts = "post/:slug"
  tweets = "tweet/:slug"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup.goldmark.renderer]
  # so that we can use raw <a> links with rel=me in homepage
  unsafe = true
