baseURL = 'http://www.williballenthin.com'
languageCode = 'en-us'
title = 'Willi Ballenthin'

theme = 'wb'

googleAnalytics = 'G-354515685'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup.goldmark.renderer]
  # so that we can use raw <a> links with rel=me in homepage
  unsafe = true
