baseURL = 'http://www.williballenthin.com'
languageCode = 'en-us'
title = 'Willi Ballenthin'

theme = 'wb'
relativeURLs = true

[permalinks]
  # use old post path to keep existing links working
  posts = "post/:slug"
  # for consistency
  links = "link/:slug"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup.goldmark.renderer]
  # so that we can use raw <a> links with rel=me in homepage
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'modus-operandi'
    tabWidth = 4

# RSS configuration
rssLimit = 100  # Show more posts in RSS feeds

[params]
  # RSS feeds should include full content for IDA plugins section
  rssFullText = true
