isort:
    uvx isort --length-sort --profile black --line-length 120 *.py

black:
    uvx black --line-length 120 *.py

ruff:
    uvx ruff check --line-length 120 *.py

mypy:
    uvx mypy --check-untyped-defs --ignore-missing-imports *.py

lint:
    -just isort
    -just black
    -just ruff
    -just mypy
