application: static-web
version: 1
runtime: python
api_version: 1

handlers:

- url: /tor/.*
  script: tor/tor_handler.py

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static



