on: [push, pull_request]

name: CI

jobs:
  deploy:
    name: deploy
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.60.1'
    - name: build
      run: hugo --theme hugo-theme-basic
    - name: cleanup
      run: |
        mv public /tmp/
        rm *
        mv /tmp/public/* .
    - name: deploy
      uses: peter-evans/s3-backup@v1.0.0
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        MIRROR_TARGET: www.williballenthin.com
        MIRROR_SOURCE: ./public 
      with:
        args: --overwrite --remove
