on: [push, pull_request]

name: CI

jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.60.1'
    - name: build
      run: hugo --minify
